cdparanoia: Ignore discarded-qualifiers coming from the header (again)
Followup to 75872c802b990a59fb327a546543824668d5485e , clang version

While we ignore `discarded-qualifiers` already for gcc, clang seems
to assign this error to `incompatible-pointer-types-discards-qualifiers`
so we need to ignore that as well.

```
In file included from \
../subprojects/gst-plugins-base/ext/cdparanoia/gstcdparanoiasrc.h:37: \
/usr/include/cdda/cdda_interface.h:164:3: error: initializing 'char *' with an expression \
of type 'const char [8]' discards qualifiers [-Werror, \
-Wincompatible-pointer-types-discards-qualifiers]
  "Success",
  ^~~~~~~~~
```

See 75872c802b990a59fb327a546543824668d5485e for more

Part-of: <https://gitlab.freedesktop.org/gstreamer/gstreamer/-/merge_requests/5474>